# Local HOL
# Create: conda env create -f .devcontainer/codespace_environment.yml
# Activate: conda activate hol-timeseries
# Remove: conda remove -n hol-timeseries --all

name: hol-timeseries
channels:
  - https://repo.anaconda.com/pkgs/snowflake
dependencies:
  - python=3.11
  - snowflake-snowpark-python[secure-local-storage,pandas]=1.36.0
  - altair=5.5.0
  - pandas=2.3.1
  - plotly=6.0.1
  - tsdownsample=0.1.3
  - setuptools=78.1.1
  - h5py=3.12.1
  - notebook=7.4.4
  - openpyxl=3.1.5
  - matplotlib=3.10.0
  - pip
  - pip:
    - streamlit==1.48.0
    - streamlit-extras==0.6.0
    - snowflake-cli==3.15.0
    - pyarrow==18.1.0
    - snowpipe-streaming==1.1.2